IF
	CheckStatGT(Player6,75,21)
	OR (2)
		CheckStatGT(Player6,85,21)
		!Kit(Player6,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player6,ApplySpellRes("TB#resi1",Player6))
		Continue()
END

IF
	CheckStatGT(Player5,75,21)
	OR (2)
		CheckStatGT(Player5,85,21)
		!Kit(Player5,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player5,ApplySpellRes("TB#resi1",Player5))
		Continue()
END

IF
	CheckStatGT(Player4,75,21)
	OR (2)
		CheckStatGT(Player4,85,21)
		!Kit(Player4,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player4,ApplySpellRes("TB#resi1",Player4))
		Continue()
END

IF
	CheckStatGT(Player3,75,21)
	OR (2)
		CheckStatGT(Player3,85,21)
		!Kit(Player3,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player3,ApplySpellRes("TB#resi1",Player3))
		Continue()
END

IF
	CheckStatGT(Player2,75,21)
	OR (2)
		CheckStatGT(Player2,85,21)
		!Kit(Player2,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player2,ApplySpellRes("TB#resi1",Player2))
		Continue()
END

IF
	CheckStatGT(Player1,75,21)
	OR (2)
		CheckStatGT(Player1,85,21)
		!Kit(Player1,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player1,ApplySpellRes("TB#resi1",Player1))
		Continue()
END

IF
	CheckStatGT(Player6,75,22)
	OR (2)
		CheckStatGT(Player6,85,22)
		!Kit(Player6,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player6,ApplySpellRes("TB#resi2",Player6))
		Continue()
END

IF
	CheckStatGT(Player5,75,22)
	OR (2)
		CheckStatGT(Player5,85,22)
		!Kit(Player5,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player5,ApplySpellRes("TB#resi2",Player5))
		Continue()
END

IF
	CheckStatGT(Player4,75,22)
	OR (2)
		CheckStatGT(Player4,85,22)
		!Kit(Player4,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player4,ApplySpellRes("TB#resi2",Player4))
		Continue()
END

IF
	CheckStatGT(Player3,75,22)
	OR (2)
		CheckStatGT(Player3,85,22)
		!Kit(Player3,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player3,ApplySpellRes("TB#resi2",Player3))
		Continue()
END

IF
	CheckStatGT(Player2,75,22)
	OR (2)
		CheckStatGT(Player2,85,22)
		!Kit(Player2,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player2,ApplySpellRes("TB#resi2",Player2))
		Continue()
END

IF
	CheckStatGT(Player1,75,22)
	OR (2)
		CheckStatGT(Player1,85,22)
		!Kit(Player1,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player1,ApplySpellRes("TB#resi2",Player1))
		Continue()
END

IF
	CheckStatGT(Player6,75,23)
	OR (2)
		CheckStatGT(Player6,85,23)
		!Kit(Player6,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player6,ApplySpellRes("TB#resi3",Player6))
		Continue()
END

IF
	CheckStatGT(Player5,75,23)
	OR (2)
		CheckStatGT(Player5,85,23)
		!Kit(Player5,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player5,ApplySpellRes("TB#resi3",Player5))
		Continue()
END

IF
	CheckStatGT(Player4,75,23)
	OR (2)
		CheckStatGT(Player4,85,23)
		!Kit(Player4,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player4,ApplySpellRes("TB#resi3",Player4))
		Continue()
END

IF
	CheckStatGT(Player3,75,23)
	OR (2)
		CheckStatGT(Player3,85,23)
		!Kit(Player3,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player3,ApplySpellRes("TB#resi3",Player3))
		Continue()
END

IF
	CheckStatGT(Player2,75,23)
	OR (2)
		CheckStatGT(Player2,85,23)
		!Kit(Player2,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player2,ApplySpellRes("TB#resi3",Player2))
		Continue()
END

IF
	CheckStatGT(Player1,75,23)
	OR (2)
		CheckStatGT(Player1,85,23)
		!Kit(Player1,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player1,ApplySpellRes("TB#resi3",Player1))
		Continue()
END

IF
	CheckStatGT(Player6,75,24)
	OR (2)
		CheckStatGT(Player6,85,24)
		!Kit(Player6,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player6,ApplySpellRes("TB#resi4",Player6))
		Continue()
END

IF
	CheckStatGT(Player5,75,24)
	OR (2)
		CheckStatGT(Player5,85,24)
		!Kit(Player5,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player5,ApplySpellRes("TB#resi4",Player5))
		Continue()
END

IF
	CheckStatGT(Player4,75,24)
	OR (2)
		CheckStatGT(Player4,85,24)
		!Kit(Player4,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player4,ApplySpellRes("TB#resi4",Player4))
		Continue()
END

IF
	CheckStatGT(Player3,75,24)
	OR (2)
		CheckStatGT(Player3,85,24)
		!Kit(Player3,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player3,ApplySpellRes("TB#resi4",Player3))
		Continue()
END

IF
	CheckStatGT(Player2,75,24)
	OR (2)
		CheckStatGT(Player2,85,24)
		!Kit(Player2,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player2,ApplySpellRes("TB#resi4",Player2))
		Continue()
END

IF
	CheckStatGT(Player1,75,24)
	OR (2)
		CheckStatGT(Player1,85,24)
		!Kit(Player1,BARBARIAN)
THEN
	RESPONSE #100
		ActionOverride(Player1,ApplySpellRes("TB#resi4",Player1))
		Continue()
END

